# Generated by Django 4.1.13 on 2024-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('clockin_time', models.TimeField(blank=True, max_length=20, null=True)),
                ('clockout_time', models.TimeField(blank=True, max_length=20, null=True)),
                ('clockin_date', models.DateField(blank=True, null=True)),
                ('clockout_date', models.DateField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('hour_worked', models.CharField(default='00:00:00', max_length=20)),
                ('day_present', models.IntegerField(default=0)),
                ('leave', models.IntegerField(default=1)),
                ('status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('role', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
