# Generated by Django 4.1.13 on 2024-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='status',
            new_name='request_status',
        ),
    ]
