# Generated by Django 4.1.13 on 2024-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_status_leave_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='request_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
