# Generated by Django 4.1.13 on 2024-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_leave_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=1024)),
                ('clockin_time', models.TimeField(blank=True, max_length=20, null=True)),
                ('clockout_time', models.TimeField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour_worked', models.CharField(default='00:00:00', max_length=20)),
                ('comments', models.CharField(max_length=2048)),
                ('tasks', models.JSONField(default=list)),
            ],
        ),
    ]
