# Generated by Django 4.1.13 on 2024-03-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
