# Generated by Django 4.1.13 on 2024-03-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_timesheet_timesheet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='date',
            new_name='submitdate',
        ),
    ]
