# Generated by Django 4.1.13 on 2024-03-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_date_timesheet_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='comments',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hour_worked',
            field=models.CharField(max_length=20),
        ),
    ]
