# Generated by Django 4.1.13 on 2024-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_timesheet_comments_alter_timesheet_hour_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='comments',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
