# Generated by Django 4.1.13 on 2024-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_timesheet_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('employee_email', models.CharField(max_length=255)),
                ('emergencycontact_name', models.CharField(max_length=255)),
                ('emergencycontact_relationship', models.CharField(max_length=255)),
                ('emergencycontact_phone', models.CharField(max_length=255)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employee_type', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('jod_title', models.CharField(max_length=255)),
                ('position_supervisor', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('pay_frequency', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_ifsc_code', models.CharField(max_length=255)),
                ('benefits_enrollment', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=255)),
                ('uan_number', models.CharField(max_length=255)),
                ('tax_filling_status', models.CharField(max_length=255)),
                ('work_authorization', models.CharField(max_length=255)),
                ('visa_status', models.CharField(max_length=255)),
                ('educational_qualification', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('skills', models.CharField(max_length=255)),
                ('performance_reviews', models.CharField(max_length=255)),
                ('training_history', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
