# Generated by Django 4.1.13 on 2024-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_employee_details_benefits_enrollment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='jod_title',
            new_name='job_title',
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='uan_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
