# Generated by Django 4.1.13 on 2024-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_jod_title_employee_details_job_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='attendance_status',
        ),
    ]
